# Generated by Django 4.2.2 on 2023-06-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
