# Generated by Django 4.2.2 on 2023-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_telegram_chat_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('ADMIN', 'Admin'), ('USER', 'User')], default='GUEST', max_length=16),
        ),
    ]
