# Generated by Django 4.2.2 on 2023-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_name_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_for_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('GUEST', 'Guest'), ('ADMIN', 'Admin')], default='GUEST', max_length=16),
        ),
    ]
