# Generated by Django 4.2.2 on 2023-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_name_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('USER', 'User'), ('ADMIN', 'Admin')], default='GUEST', max_length=16),
        ),
    ]
