# Generated by Django 4.2.2 on 2023-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Неизвестный', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Пользователь', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_for_access',
            field=models.BooleanField(default=False, verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('guest', 'Гость'), ('admin', 'Администратор')], default='guest', max_length=16, verbose_name='Права пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграмм id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним'),
        ),
    ]
