# Generated by Django 4.2.2 on 2023-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('guest', 'Guest'), ('admin', 'Admin')], default='guest', max_length=16, verbose_name='Права пользователя'),
        ),
    ]
