# Generated by Django 4.2.2 on 2023-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграмм id'),
        ),
    ]
