# Generated by Django 4.2.2 on 2023-06-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IP', 'in_progress'), ('D', 'done'), ('C', 'cancelled')], default='IP', max_length=256),
        ),
    ]
