# Generated by Django 4.2.2 on 2023-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_cart_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='in_progress', max_length=256, verbose_name='Статус заказа'),
        ),
    ]
